// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmukjqpxzzwauseinrzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtdWtqcXB4enp3YXVzZWlucnp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MDQ2NDYsImV4cCI6MjA1NTE4MDY0Nn0.CS2hyDE4rrAI14kqSat5jRuFE0i9TutcDvA8_D8FVe4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);